CREATE TABLE hello
(
    hello_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    create_by   VARCHAR(50)                             NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    modified_by VARCHAR(50),
    version     INTEGER                                 NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_hello PRIMARY KEY (hello_id)
);

ALTER TABLE hello
    ADD CONSTRAINT uc_hello_name UNIQUE (name);