DROP SEQUENCE IF EXISTS ACCOUNT_SEQ;

CREATE SEQUENCE ACCOUNT_SEQ START WITH 1 INCREMENT BY 10;

DROP TABLE IF EXISTS ACCOUNT CASCADE;

CREATE TABLE ACCOUNT
(
    ACCOUNT_ID  BIGINT                      NOT NULL,
    CREATED_AT  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CREATE_BY   VARCHAR(50)                 NOT NULL,
    MODIFIED_AT TIMESTAMP WITHOUT TIME ZONE,
    MODIFIED_BY VARCHAR(50),
    VERSION     INTEGER,
    EMAIL       VARCHAR(100)                NOT NULL,
    PASSWORD    VARCHAR(62)                 NOT NULL,
    ROLE        VARCHAR(255),
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNT_ID)
);

ALTER TABLE ACCOUNT
    ADD CONSTRAINT UC_ACCOUNT_EMAIL UNIQUE (EMAIL);

ALTER TABLE ACCOUNT
    ADD CONSTRAINT UC_ACCOUNT_PASSWORD UNIQUE (PASSWORD);