server:
  port: 8080

spring:
  application:
    name: CoupleRings
  profiles:
    active: ${CPLERINGS_PROFILES_ACTIVE}
  datasource:
    url: jdbc:postgresql://${CPLERINGS_DATABASE_URL}:${CPLERINGS_DATABASE_PORT}/${CPLERINGS_DATABASE_NAME}
    username: ${CPLERINGS_DATABASE_USERNAME}
    password: ${CPLERINGS_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 10
        format_sql: true
        show_sql: true
        order_updates: true
        jdbc:
          fetch_size: 10
          batch_size: 10
  flyway:
    url: jdbc:postgresql://${CPLERINGS_DATABASE_URL}:${CPLERINGS_DATABASE_PORT}/${CPLERINGS_DATABASE_NAME}
    user: ${CPLERINGS_DATABASE_USERNAME}
    password: ${CPLERINGS_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    locations: classpath:db/migration/prod
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CPLERINGS_EMAIL}
    password: ${CPLERINGS_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

---

spring:
  config:
    activate:
      on-profile: dev,local
  flyway:
    locations: classpath:db/migration/prod,classpath:db/migration/dev

---

spring:
  config:
    activate:
      on-profile: prod
  flyway:
    locations: classpath:db/migration/prod

---

cplerings:
  api:
    path: /api/v1
  jwt:
    secret: ${CPLERINGS_JWT_SECRET}
    duration: ${CPLERINGS_JWT_DURATION}
    refreshDuration: ${CPLERINGS_JWT_REFRESH_DURATION}
  locale: ${CPLERINGS_LOCALE}
springdoc:
  api-docs:
    path: ${cplerings.api.path}/docs
  swagger-ui:
    path: ${springdoc.api-docs.path}/ui