name: Deploys DEV-CORE
on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  check-if-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is merged into develop
        if: github.event.pull_request.merged
        run: exit 0

  unit-testing:
    needs: [check-if-merge]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Run Unit Tests
        run: mvn clean test

  integration-testing:
    needs: [check-if-merge]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Run Integration Tests
        run: mvn clean verify

  deploy:
    needs: [unit-testing, integration-testing]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: cplerings/cplerings-core-dev:latest